### PR TITLE
fix: handle parsing versions from RPM >= 4.15

### LINKED ISSUE #163: Cannot check version for RPM >= 4.15
**What version of `electron-installer-redhat` are you using?**

3.0.0

**What version of `node` and `npm` are you using?**

node v14.3.0  
npm 6.14.5

**What operating system are you using?**

Linux - Fedora 32 (Workstation Edition)

**Can you compile the [example app](https://github.com/unindented/electron-installer-redhat/tree/master/example) successfully?**

Haven't tried

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-redhat.git
$ cd electron-installer-redhat/example
$ DEBUG='electron-installer-redhat' npm run build
```

n/a

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**

        {
          "name": "@electron-forge/maker-rpm",
          "config": {
            "options": {
              "icon": "./assets/images/[some-image].png"
            }
          }
        }

**What did you expect to happen?**

a RPM to be built

**What actually happened?**

The installer crashes because the RPM version output cannot be parsed; `RPM-Version 4.15.1` contains only one space, the installer expects 2.

### PR DESCRIPTION
**Pull request by dtanzer**
"npm run make" crashes when the rpmbuild version is `[ 'RPM-Version', '4.15.1' ]`. With this fix, we always take the last part of the version string, which should be the version number.

On my system, the output of `rpmbuild --version` only contains a single string: `RPM-Version 4.15.1`. In this case, making the project crashes with the error message `Cannot read property 'split' of undefined`.

This change always takes the last part of the version string to compare the version number instead of using the hard-coded value `2` as an index - which might not exist.

I am running on:

```
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
```

Fixes #163.

### CODE REVIEW

**Comment by dtanzer** [comment]
I have fixed the eslint error - but I have no idea how to write a test for that. I would have to either
* stub `global.spawn` which causes some problmes or
* completely restructure the code to have a function that _only_ gets the version number from the output of `spawn`; and then I'd only test the string.split function, which is pretty boring

File: src/dependencies.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ const dependencyMap = {
 async function rpmSupportsBooleanDependencies (logger) {
   const output = await spawn('rpmbuild', ['--version'], logger)
   const parts = output.trim().split(' ')
-  return rpmVersionSupportsBooleanDependencies(parts[parts.length-1])
+  return rpmVersionSupportsBooleanDependencies(parts[parts.length - 1])
```
Comment (malept) [inline src/dependencies.js:31]:
```suggestion
  return rpmVersionSupportsBooleanDependencies(parts.slice(-1))
```

**Comment by dtanzer** [comment]
Finally found out why stubbing did not work in my first tests - the production code did not use the stubbed values, now it does.

I have applied your change and added some tests, but "slice" returns an array so I also had to access the 0-th element. Not sure it is better.

File: src/dependencies.js [hunk 2]
```diff
@@ -21,13 +21,20 @@ const dependencyMap = {
...
  * Retrieves the RPM version number and determines whether it has support for boolean
  * dependencies (>= 4.13.0).
  */
 async function rpmSupportsBooleanDependencies (logger) {
-  const output = await spawn('rpmbuild', ['--version'], logger)
-  return rpmVersionSupportsBooleanDependencies(output.trim().split(' ')[2])
+  const output = await module.exports.spawnRpmBuild(logger)
+
+  const parts = output.trim().split(' ')
+  const versionNumber = parts.slice(-1)[0]
```
Comment (malept) [inline src/dependencies.js:35]:
```suggestion
  const versionNumber = _.last(parts)
```

And add `const _ = require('lodash')` at the top, in alphabetical order.

File: src/dependencies.js [hunk 3]
```diff
@@ -21,13 +21,20 @@ const dependencyMap = {
   xtst: '(libXtst or libXtst6)'
 }
 
+async function spawnRpmBuild (logger) {
```
Comment (malept) [inline src/dependencies.js:24]:
```suggestion
async function getRpmVersion (logger) {
```

File: src/dependencies.js [hunk 4]
```diff
@@ -21,13 +21,20 @@ const dependencyMap = {
...
+  return await spawn('rpmbuild', ['--version'], logger)
```
Comment (malept) [inline src/dependencies.js:25]:
```suggestion
  return spawn('rpmbuild', ['--version'], logger)
```

File: test/dependencies.js [hunk 5]
```diff
@@ -22,6 +22,26 @@ describe('dependencies', () => {
...
+
+      it(`parses RPM version output "${versionString}" (with ${parts} parts) correctly`, async () => {
+        sinon.stub(dependencies, 'spawnRpmBuild').resolves(versionString)
+        const stub = sinon.stub(dependencies, 'rpmVersionSupportsBooleanDependencies')
+
+        await dependencies.rpmSupportsBooleanDependencies(null)
+        sinon.assert.calledWith(stub, '4.15.1')
+      })
+    })
+  })
```
Comment (malept) [inline test/dependencies.js:43]: I don't think the tests need to be this meta. It's better to test against real-world data anyway.
```suggestion
  describe('getRpmVersion', () => {
    it('parses version output from RPM < 4.15', async () => {
      const versionOutput = 'RPM version 4.14.2.1\n'
      // stub spawn
      expect(dependencies.getRpmVersion()).to.equal('4.14.2.1')
    })
    
    it('parses version output from RPM >= 4.15', async () => {
      const versionOutput = 'RPM-Version 4.15.1\n'
      // stub spawn
      expect(dependencies.getRpmVersion()).to.equal('4.15.1')
    })
  })
```

File: src/dependencies.js [hunk 6]
```diff
@@ -21,13 +22,21 @@ const dependencyMap = {
   xtst: '(libXtst or libXtst6)'
 }
 
+async function getRpmVersion (logger, spawnProgram = spawn) {
```
Comment (malept) [inline src/dependencies.js:25]: I'd rather add [`proxyquire`](https://www.npmjs.com/package/proxyquire) to `devDependencies` than add arguments that only get changed for testing purposes.
```suggestion
async function getRpmVersion (logger) {
```

**Comment by dtanzer** [comment]
I do not like this change because the code violates the Dependency Inversion Principle again. I was trying to make a dependency explicit, while proxyrequire hides the problem under another layer of magic. IMHO, it would be slightly better to change the default export of spawn to a named export and mock that, but that would still violate the DIP.

Anyway, you can implement the fix however you want. I understand that you have to keep this repository clean in a way that you prefer, because you have to work with it daily. So I **do** understand why we are having this conversation.

But we both have already spent too many hours on a one-line change - A change that you could have tested and implemented the way you want it in minutes. I cannot work on this PR any longer, but I have submitted a bug report: https://github.com/electron-userland/electron-installer-redhat/issues/163

**Comment by malept** [comment]
Thanks for your contribution!
